steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/roman-numeral-app', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/roman-numeral-app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'roman-numeral-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/roman-numeral-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--timeout'
      - '300s'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/roman-numeral-app' 