services:
  backend:
    build:
      context: ./backend
      args:
        - BACKEND_PORT=${BACKEND_PORT:-3131}
        - FRONTEND_PORT=${FRONTEND_PORT:-5151}
        - FRONTEND_HOST=${FRONTEND_HOST:-localhost}
    ports:
      - "${BACKEND_PORT:-3131}:${BACKEND_PORT:-3131}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-3131}
      - FRONTEND_PORT=${FRONTEND_PORT:-5151}
      - FRONTEND_HOST=${FRONTEND_HOST:-localhost}
      - NODE_ENV=production
      - LOG_LEVEL=INFO