# Define environment variables at the root level
x-environment: &environment
  BACKEND_PORT: 3131
  FRONTEND_PORT: 5151
  BACKEND_HOST: localhost
  FRONTEND_HOST: localhost

services:
  # Combined app
  roman-numeral-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_HOST=${BACKEND_HOST:-localhost}
        - VITE_BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=${BACKEND_PORT}
      - LOG_LEVEL=INFO
      - FRONTEND_HOST=${FRONTEND_HOST:-localhost}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_BACKEND_HOST=${BACKEND_HOST:-localhost}
      - VITE_BACKEND_PORT=${BACKEND_PORT} 